using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataGenerationEngine.Model
{
    internal static class MockDataLibrary
    {
        static MockDataLibrary()
        {
        }

        public static string[] Address1s = new string[]{"324 Baker St.",
                                                        "21 Jump St.",
                                                        "2002 Summit Blvd",
                                                        "189 Main St.",
                                                        "739 Pine Ave"};

        public static string[] Address2s = new string[]{"Ste. 293",
                                                           "Bldg. G",
                                                           "Apt 6701",
                                                           "Lodge 9",
                                                           "Ste. 700"};

        public static string[] CompanyNames = new string[]{"Aamco Inc.",
                                                           "Ben's Hardware Co.",
                                                           "Gilley Co.",
                                                           "Steagle Glass and Steel Inc.",
                                                           "Zanax Scanning LLC."};

        public static string[] FirstNames = new string[]{"Angela",
                                                           "Anthony",
                                                           "Bonnie",
                                                           "Manoj",
                                                           "Micheal",
                                                           "Spencer",
                                                           "Vladimir"};

        public static string[] LastNames = new string[]{"Daniels",
                                                           "Udosen",
                                                           "Walker",
                                                           "Parker",
                                                           "Brown",
                                                           "Smith"};

        public static string[] Cities = new string[]{"Monsey",
                                                    "Kingston",
                                                    "Rio Bravo",
                                                    "Rexburg",
                                                    "Lackland AFB",
                                                    "South Hill",
                                                    "Alfred",
                                                    "Storrs",
                                                    "Amherst Center",
                                                    "Durham",
                                                    "Whiteriver",
                                                    "Highland",
                                                    "Cameron Park",
                                                    "Alpine",
                                                    "Isla Vista",
                                                    "Allendale",
                                                    "West Point",
                                                    "Twentynine Palms Base",
                                                    "Geneseo",
                                                    "Durham",
                                                    "Oxford",
                                                    "Fort Hood",
                                                    "Fort Campbell North",
                                                    "Fort Leonard Wood",
                                                    "Camp Pendleton North",
                                                    "Boone",
                                                    "Athens",
                                                    "Oswego",
                                                    "Geneseo",
                                                    "Potsdam",
                                                    "Offutt AFB",
                                                    "Fort Stewart",
                                                    "Clarion",
                                                    "Elon College",
                                                    "East Lansing",
                                                    "La Homa",
                                                    "College Park",
                                                    "Ettrick",
                                                    "Fort Lee",
                                                    "Houghton",
                                                    "Camp Pendleton South",
                                                    "Big Rapids",
                                                    "Indiana",
                                                    "Amherst",
                                                    "Fort Riley North",
                                                    "State College",
                                                    "Hamilton",
                                                    "Edinboro",
                                                    "Mount Pleasant",
                                                    "Whitewater",
                                                    "Canton",
                                                    "College Station",
                                                    "Hanover",
                                                    "Chinle",
                                                    "Blacksburg",
                                                    "Earlimart",
                                                    "Plymouth",
                                                    "Fort Bliss",
                                                    "Lemoore Station",
                                                    "North Chicago",
                                                    "Kaneohe Station",
                                                    "Minot AFB",
                                                    "Mansfield",
                                                    "Ada",
                                                    "Statesboro",
                                                    "Ithaca",
                                                    "Fort Polk South",
                                                    "Orono",
                                                    "Fort Bragg",
                                                    "Fort Knox",
                                                    "Eglin AFB",
                                                    "Schofield Barracks",
                                                    "Stanford",
                                                    "Fort Carson",
                                                    "New Paltz",
                                                    "North Amherst",
                                                    "Eielson AFB",
                                                    "Orono",
                                                    "West Lafayette",
                                                    "Lewisburg",
                                                    "Homestead Meadows South",
                                                    "Bloomsburg",
                                                    "Jacksonville",
                                                    "McGuire AFB",
                                                    "Millersville",
                                                    "Bowling Green",
                                                    "Quantico Station",
                                                    "Brockport",
                                                    "Fort Lewis",
                                                    "Farmville",
                                                    "Lindon",
                                                    "Fort Benning South",
                                                    "Fort Drum",
                                                    "Pullman",
                                                    "San Elizario",
                                                    "Monroe",
                                                    "Fort Belvoir",
                                                    "Williamsburg"};

public static string[] States = new string[]{"Alabama",
                                            "Alaska",
                                            "Arizona",
                                            "Arkansas",
                                            "California",
                                            "Colorado",
                                            "Connecticut",
                                            "Delaware",
                                            "District Of Columbia",
                                            "Florida",
                                            "Georgia",
                                            "Hawaii",
                                            "Idaho",
                                            "Illinois",
                                            "Indiana",
                                            "Iowa",
                                            "Kansas",
                                            "Kentucky",
                                            "Louisiana",
                                            "Maine",
                                            "Maryland",
                                            "Massachusetts",
                                            "Michigan",
                                            "Minnesota",
                                            "Mississippi",
                                            "Missouri",
                                            "Montana",
                                            "Nebraska",
                                            "Nevada",
                                            "New Hampshire",
                                            "New Jersey",
                                            "New Mexico",
                                            "New York",
                                            "North Carolina",
                                            "North Dakota",
                                            "Ohio",
                                            "Oklahoma",
                                            "Oregon",
                                            "Pennsylvania",
                                            "Rhode Island",
                                            "South Carolina",
                                            "South Dakota",
                                            "Tennessee",
                                            "Texas",
                                            "Utah",
                                            "Vermont",
                                            "Virginia",
                                            "Washington",
                                            "West Virginia",
                                            "Wisconsin",
                                            "Wyoming"};

public static string[] Counties = new string[]{"Alachua",
                                                "Baker",
                                                "Bay",
                                                "Bradford",
                                                "Brevard",
                                                "Broward",
                                                "Calhoun",
                                                "Charlotte",
                                                "Citrus",
                                                "Clay",
                                                "Collier",
                                                "Columbia",
                                                "De Soto",
                                                "Dixie",
                                                "Duval",
                                                "Escambia",
                                                "Flagler",
                                                "Franklin",
                                                "Gadsden",
                                                "Gilchrist",
                                                "Glades",
                                                "Gulf",
                                                "Hamilton",
                                                "Hardee",
                                                "Hendry",
                                                "Hernando",
                                                "Highlands",
                                                "Hillsborough",
                                                "Holmes",
                                                "Indian River",
                                                "Jackson",
                                                "Jefferson",
                                                "Lafayette",
                                                "Lake",
                                                "Lee",
                                                "Leon",
                                                "Levy",
                                                "Liberty",
                                                "Madison",
                                                "Manatee",
                                                "Marion",
                                                "Martin",
                                                "Miami-Dade",
                                                "Monroe",
                                                "Nassau",
                                                "Okaloosa",
                                                "Okeechobee",
                                                "Orange",
                                                "Osceola",
                                                "Palm Beach",
                                                "Pasco",
                                                "Pinellas",
                                                "Polk",
                                                "Putnam",
                                                "Santa Rosa",
                                                "Sarasota",
                                                "Seminole",
                                                "St. Johns",
                                                "St. Lucie",
                                                "Sumter",
                                                "Suwannee",
                                                "Taylor",
                                                "Union",
                                                "Volusia",
                                                "Wakulla",
                                                "Walton",
                                                "Washington",
                                                "Georgia",
                                                "Appling",
                                                "Atkinson",
                                                "Bacon",
                                                "Baker",
                                                "Baldwin",
                                                "Banks",
                                                "Barrow",
                                                "Bartow",
                                                "Ben Hill",
                                                "Berrien",
                                                "Bibb",
                                                "Bleckley",
                                                "Brantley",
                                                "Brooks",
                                                "Bryan",
                                                "Bullock",
                                                "Burke",
                                                "Butts",
                                                "Calhoun",
                                                "Camden",
                                                "Candler",
                                                "Carroll",
                                                "Catoosa",
                                                "Charlton",
                                                "Chatahoochee",
                                                "Chatham",
                                                "Chattooga",
                                                "Cherokee",
                                                "Clarke",
                                                "Clay",
                                                "Clayton",
                                                "Clinch",
                                                "Cobb",
                                                "Coffee",
                                                "Colquitt",
                                                "Columbia",
                                                "Cook",
                                                "Coweta",
                                                "Crawford",
                                                "Crisp",
                                                "Dade",
                                                "Dawson",
                                                "De Kalb",
                                                "Decatur",
                                                "Dodge",
                                                "Dooly",
                                                "Dougherty",
                                                "Douglas",
                                                "Early",
                                                "Echols",
                                                "Effingham",
                                                "Elbert",
                                                "Emanuel",
                                                "Evans",
                                                "Fannin",
                                                "Fayette",
                                                "Floyd",
                                                "Forsyth",
                                                "Franklin",
                                                "Fulton",
                                                "Gilmer",
                                                "Glascock",
                                                "Glynn",
                                                "Gordon",
                                                "Grady",
                                                "Greene",
                                                "Gwinnett",
                                                "Habersham",
                                                "Hall",
                                                "Hancock",
                                                "Haralson",
                                                "Harris",
                                                "Hart",
                                                "Heard",
                                                "Henry",
                                                "Houston",
                                                "Irwin",
                                                "Jackson",
                                                "Jasper",
                                                "Jeff Davis",
                                                "Jefferson",
                                                "Jenkins",
                                                "Johnson",
                                                "Jones",
                                                "Lamar",
                                                "Lanier",
                                                "Laurens",
                                                "Lee",
                                                "Liberty",
                                                "Lincoln",
                                                "Long",
                                                "Lowndes",
                                                "Lumpkin",
                                                "Macon",
                                                "Madison",
                                                "Marion",
                                                "Mcduffie",
                                                "Mcintosh",
                                                "Meriwether",
                                                "Miller",
                                                "Mitchell",
                                                "Monroe",
                                                "Montgomery",
                                                "Morgan",
                                                "Murray",
                                                "Muscogee",
                                                "Newton",
                                                "Oconee",
                                                "Oglethorpe",
                                                "Orange",
                                                "Paulding",
                                                "Peach",
                                                "Pickens",
                                                "Pierce",
                                                "Pike",
                                                "Polk",
                                                "Pulaski",
                                                "Putnam",
                                                "Quitman",
                                                "Rabun",
                                                "Randolph",
                                                "Richmond",
                                                "Rockdale",
                                                "Schley",
                                                "Screven",
                                                "Seminole",
                                                "Spalding",
                                                "Stephens",
                                                "Stewart",
                                                "Sumter",
                                                "Talbot",
                                                "Taliaferro",
                                                "Tattnall",
                                                "Taylor",
                                                "Telfair",
                                                "Terrell",
                                                "Thomas",
                                                "Tift",
                                                "Toombs",
                                                "Towns",
                                                "Treutlen",
                                                "Troup",
                                                "Turner",
                                                "Twiggs",
                                                "Union",
                                                "Upson",
                                                "Walker",
                                                "Walton",
                                                "Ware",
                                                "Warren",
                                                "Washington",
                                                "Wayne",
                                                "Webster",
                                                "Wheeler",
                                                "White",
                                                "Whitfield",
                                                "Wilcox",
                                                "Wilkes",
                                                "Wilkinson",
                                                "Worth"};

public static string[] Countries = new string[]{"Albania",
                                        "Algeria",
                                        "Andorra",
                                        "Angola",
                                        "Antigua",
                                        "Argentina",
                                        "Armenia",
                                        "Australia",
                                        "Austria",
                                        "Azerbaijan",
                                        "Bahamas",
                                        "Bahrain",
                                        "Bangladesh",
                                        "Barbados",
                                        "Belarus",
                                        "Belgium",
                                        "Belize",
                                        "Benin",
                                        "Bhutan",
                                        "Bolivia",
                                        "Bosnia",
                                        "Botswana",
                                        "Brazil",
                                        "Brunei",
                                        "Bulgaria",
                                        "Burkina",
                                        "Burundi",
                                        "Cambodia",
                                        "Cameroon",
                                        "Canada",
                                        "Cape",
                                        "Central",
                                        "Chad",
                                        "Chile",
                                        "China",
                                        "Colombia",
                                        "Comoros",
                                        "Congo",
                                        "Congo,",
                                        "Costa",
                                        "Côte",
                                        "Croatia",
                                        "Cuba",
                                        "Cyprus",
                                        "Czech",
                                        "Denmark",
                                        "Djibouti",
                                        "Dominica",
                                        "Dominican",
                                        "East",
                                        "Ecuador",
                                        "Egypt",
                                        "El",
                                        "Equatorial",
                                        "Eritrea",
                                        "Estonia",
                                        "Ethiopia",
                                        "Fiji",
                                        "Finland",
                                        "France",
                                        "Gabon",
                                        "Gambia,",
                                        "Georgia",
                                        "Germany",
                                        "Ghana",
                                        "Greece",
                                        "Grenada",
                                        "Guatemala",
                                        "Guinea",
                                        "Guinea-Bissau",
                                        "Guyana",
                                        "Haiti",
                                        "Honduras",
                                        "Hungary",
                                        "Iceland",
                                        "India",
                                        "Indonesia",
                                        "Iran",
                                        "Iraq",
                                        "Ireland",
                                        "Israel",
                                        "Italy",
                                        "Jamaica",
                                        "Japan",
                                        "Jordan",
                                        "Kazakhstan",
                                        "Kenya",
                                        "Kiribati",
                                        "Korea,",
                                        "Korea,",
                                        "Kuwait",
                                        "Kyrgyzstan",
                                        "Laos",
                                        "Latvia",
                                        "Lebanon",
                                        "Lesotho",
                                        "Liberia",
                                        "Libya",
                                        "Liechtenstein",
                                        "Lithuania",
                                        "Luxembourg",
                                        "Madagascar",
                                        "Malawi",
                                        "Malaysia",
                                        "Maldives",
                                        "Mali",
                                        "Malta",
                                        "Marshall",
                                        "Mauritania",
                                        "Mauritius",
                                        "Mexico",
                                        "Micronesia,",
                                        "Moldova",
                                        "Monaco",
                                        "Mongolia",
                                        "Montenegro",
                                        "Morocco",
                                        "Mozambique",
                                        "Myanmar",
                                        "Namibia",
                                        "Nauru",
                                        "Nepal",
                                        "Netherlands",
                                        "New",
                                        "Nicaragua",
                                        "Niger",
                                        "Nigeria",
                                        "Norway",
                                        "Oman",
                                        "Pakistan",
                                        "Palau",
                                        "Panama",
                                        "Papua",
                                        "Paraguay",
                                        "Peru",
                                        "Philippines",
                                        "Poland",
                                        "Portugal",
                                        "Qatar",
                                        "Republic",
                                        "Romania",
                                        "Russia",
                                        "Rwanda",
                                        "Saint",
                                        "Saint",
                                        "Saint",
                                        "Samoa",
                                        "San",
                                        "Sao",
                                        "Saudi",
                                        "Senegal",
                                        "Serbia",
                                        "Seychelles",
                                        "Sierra",
                                        "Singapore",
                                        "Slovakia",
                                        "Slovenia",
                                        "Solomon",
                                        "Somalia",
                                        "South",
                                        "Spain",
                                        "Sri",
                                        "Sudan",
                                        "Suriname",
                                        "Swaziland",
                                        "Sweden",
                                        "Switzerland",
                                        "Syria",
                                        "Taiwan",
                                        "Tajikistan",
                                        "Tanzania",
                                        "Thailand",
                                        "Togo",
                                        "Tonga",
                                        "Trinidad",
                                        "Tunisia",
                                        "Turkey",
                                        "Turkmenistan",
                                        "Tuvalu",
                                        "Uganda",
                                        "Ukraine",
                                        "United States of America",
                                        "Uruguay",
                                        "Uzbekistan",
                                        "Vanuatu",
                                        "Vatican",
                                        "Venezuela",
                                        "Vietnam",
                                        "Web",
                                        "Western",
                                        "Yemen",
                                        "Zambia",
                                        "Zimbabwe"};

    }
}
