namespace HyperStubs.Model
{
    internal static partial class StubDataLibrary
    {
        public static string[] Cities = new string[]{"Monsey",
                                                    "Kingston",
                                                    "Rio Bravo",
                                                    "Rexburg",
                                                    "Lackland AFB",
                                                    "South Hill",
                                                    "Alfred",
                                                    "Storrs",
                                                    "Amherst Center",
                                                    "Durham",
                                                    "Whiteriver",
                                                    "Highland",
                                                    "Cameron Park",
                                                    "Alpine",
                                                    "Isla Vista",
                                                    "Allendale",
                                                    "West Point",
                                                    "Twentynine Palms Base",
                                                    "Geneseo",
                                                    "Durham",
                                                    "Oxford",
                                                    "Fort Hood",
                                                    "Fort Campbell North",
                                                    "Fort Leonard Wood",
                                                    "Camp Pendleton North",
                                                    "Boone",
                                                    "Athens",
                                                    "Oswego",
                                                    "Geneseo",
                                                    "Potsdam",
                                                    "Offutt AFB",
                                                    "Fort Stewart",
                                                    "Clarion",
                                                    "Elon College",
                                                    "East Lansing",
                                                    "La Homa",
                                                    "College Park",
                                                    "Ettrick",
                                                    "Fort Lee",
                                                    "Houghton",
                                                    "Camp Pendleton South",
                                                    "Big Rapids",
                                                    "Indiana",
                                                    "Amherst",
                                                    "Fort Riley North",
                                                    "State College",
                                                    "Hamilton",
                                                    "Edinboro",
                                                    "Mount Pleasant",
                                                    "Whitewater",
                                                    "Canton",
                                                    "College Station",
                                                    "Hanover",
                                                    "Chinle",
                                                    "Blacksburg",
                                                    "Earlimart",
                                                    "Plymouth",
                                                    "Fort Bliss",
                                                    "Lemoore Station",
                                                    "North Chicago",
                                                    "Kaneohe Station",
                                                    "Minot AFB",
                                                    "Mansfield",
                                                    "Ada",
                                                    "Statesboro",
                                                    "Ithaca",
                                                    "Fort Polk South",
                                                    "Orono",
                                                    "Fort Bragg",
                                                    "Fort Knox",
                                                    "Eglin AFB",
                                                    "Schofield Barracks",
                                                    "Stanford",
                                                    "Fort Carson",
                                                    "New Paltz",
                                                    "North Amherst",
                                                    "Eielson AFB",
                                                    "Orono",
                                                    "West Lafayette",
                                                    "Lewisburg",
                                                    "Homestead Meadows South",
                                                    "Bloomsburg",
                                                    "Jacksonville",
                                                    "McGuire AFB",
                                                    "Millersville",
                                                    "Bowling Green",
                                                    "Quantico Station",
                                                    "Brockport",
                                                    "Fort Lewis",
                                                    "Farmville",
                                                    "Lindon",
                                                    "Fort Benning South",
                                                    "Fort Drum",
                                                    "Pullman",
                                                    "San Elizario",
                                                    "Monroe",
                                                    "Fort Belvoir",
                                                    "Williamsburg"};
    }
}
